services:
  mongo:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/mongo_volume
      - ./database/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./.env.db
    restart: always
  backend:
    build: ./backend
    depends_on:
      - mongo
    volumes:
      - backend:/backend
    env_file:
      - ./.env.backend
    ports:
      - 4000:4000
  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - ./.env.frontend
    ports:
      - 3000:3000
volumes:
  backend:
  mongo_volume: