services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_volume:/mongo_volume
      - ./database/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    env_file:
      - ./.env.db
  backend:
    build: ./frontend
    depends_on:
      - mongodb
    volumes:
      - ./backend:/backend
    env_file:
      - ./.env.backend
    ports:
      - 3000:3000
  frontend:
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./.env.frontend
    ports:
      - 5173:5173
volumes:
  frontend:
  backend:
  mongo_volume: