networks:
  app:
    driver: bridge

services:
  mongo:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/mongo_volume
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    networks:
      - app
      
  backend:
    build: ./backend
    depends_on:
      - mongo
    ports: 
      - 3000:3000
    env_file:
      - ./backend/.env.backend
    networks:
      - app

  frontend:
    build: ./frontend
    ports: 
      - 5173:5173
    tty: true
    env_file:
      - ./frontend/.env.frontend
    depends_on:
      - backend
    networks:
      - app
volumes:
  mongo_volume: